#!/usr/bin/env node
/**
 * Extella Toolbar — Build Script
 *
 * Reads all source modules and plugin JSON files, then outputs:
 *   build/toolbar.js            — compiled toolbar (injects into Extella Desktop)
 *   build/plugins_manager.html  — marketplace with built-in plugin data
 *   build/plugin-chat.html      — chat interface (copied as-is)
 *
 * Usage:
 *   node build.js
 *   node build.js --watch   (re-run on file changes)
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Paths ──────────────────────────────────────────────────────────────────
const ROOT    = __dirname;
const SRC     = path.join(ROOT, 'src');
const PLUGINS = path.join(ROOT, 'plugins');
const PUBLIC  = path.join(ROOT, 'public');
const OUT     = path.join(ROOT, 'build');
const DESKTOP_LOADER = path.join(ROOT, 'assets', 'desktop-loader.webm');
const BRAND_LOGO = path.join(ROOT, 'assets', 'extella-x.png');

// ── Module load order ──────────────────────────────────────────────────────
// Files are concatenated in this exact order inside the IIFE.
const CORE_ORDER = [
  'brand.js',
  'auth.js',
  'api.js',
  'install-prompt.js',
  'repo-analyzer.js',
  'hf-analyzer.js',
  'theme.js',
  'registry.js',
  'plugins.js',
  'router.js',
  'shell.js',
  'nav.js',
  'tabs.js'
];

const PANELS_ORDER = [
  'marketplace.js',
  'activity-center.js',
  'library.js',
  'github-add.js',
  'hf-add.js',
  'plugin-view.js'
];

// ── Helpers ────────────────────────────────────────────────────────────────
function readFile(p) {
  return fs.readFileSync(p, 'utf8');
}

function writeFile(p, content) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content, 'utf8');
  const kb = (Buffer.byteLength(content, 'utf8') / 1024).toFixed(1);
  console.log(`  ✓ ${path.relative(ROOT, p)} (${kb} KB)`);
}

// Walk a directory and collect all .json files recursively
function collectJsonFiles(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectJsonFiles(full));
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      results.push(full);
    }
  }
  return results;
}

// ── Step 1: Load all plugin JSON files ────────────────────────────────────
function loadPlugins() {
  const files = collectJsonFiles(PLUGINS);
  const plugins = [];
  for (const f of files) {
    try {
      const data = JSON.parse(readFile(f));
      plugins.push(data);
    } catch (e) {
      console.warn(`  ⚠ Could not parse ${f}: ${e.message}`);
    }
  }
  console.log(`  Loaded ${plugins.length} plugin definitions`);
  return plugins;
}

// ── Step 2: Build toolbar.js ───────────────────────────────────────────────
function buildToolbar(plugins) {
  const parts = [];
  const now = new Date().toISOString();

  // Build embedded HTML strings (blob URL approach — no local server needed)
  const marketplaceHtml = buildMarketplace(plugins);
  const chatHtml        = buildChat(plugins);
  const formHtml        = buildForm(plugins);
  const libraryHtml     = buildLibrary();
  const brandLogoImage = getBrandLogoData();

  // ── Banner ─────────────────────────────────────────────────────
  parts.push([
    `// Extella Toolbar v6.0 — Modular Build`,
    `// Built: ${now}`,
    `// Modules: src/core/ + src/panels/ + plugins/*.json`,
    `// DO NOT EDIT THIS FILE DIRECTLY — edit sources in src/ and run: node build.js`,
    ``
  ].join('\n'));

  // ── IIFE start ─────────────────────────────────────────────────
  parts.push(`(function () {\n  'use strict';\n\n  var ETB = {};\n`);

  // ── Embedded HTML (marketplace + plugin chat + plugin form) ───────────────
  // These are loaded as blob: URLs so no local HTTP server is required.
  parts.push(`  var _ETB_MARKETPLACE_HTML = ${JSON.stringify(marketplaceHtml)};\n`);
  parts.push(`  var _ETB_CHAT_HTML = ${JSON.stringify(chatHtml)};\n`);
  parts.push(`  var _ETB_FORM_HTML = ${JSON.stringify(formHtml)};\n`);
  parts.push(`  var _ETB_LIBRARY_HTML = ${JSON.stringify(libraryHtml)};\n`);
  parts.push(`  var _ETB_BRAND_LOGO = ${JSON.stringify(brandLogoImage)};\n`);

  // ── Built-in plugins constant ──────────────────────────────────
  parts.push(`  // Built-in plugins (injected by build.js from plugins/*.json)\n`);
  parts.push(`  var BUILTIN_PLUGINS = ${JSON.stringify(plugins, null, 2)};\n`);

  // ── Core modules ───────────────────────────────────────────────
  parts.push(`\n  // ── CORE MODULES ──────────────────────────────────────────────────────────\n`);
  for (const name of CORE_ORDER) {
    const p = path.join(SRC, 'core', name);
    if (!fs.existsSync(p)) {
      console.warn(`  ⚠ Missing core module: ${name}`);
      continue;
    }
    parts.push(`\n  // ── ${name} ─────────────────────────────────────────────────────────\n`);
    parts.push(indent(readFile(p), 2));
  }

  // ── Panel modules ──────────────────────────────────────────────
  parts.push(`\n  // ── PANEL MODULES ─────────────────────────────────────────────────────────\n`);
  for (const name of PANELS_ORDER) {
    const p = path.join(SRC, 'panels', name);
    if (!fs.existsSync(p)) {
      console.warn(`  ⚠ Missing panel module: ${name}`);
      continue;
    }
    parts.push(`\n  // ── ${name} ─────────────────────────────────────────────────────────\n`);
    parts.push(indent(readFile(p), 2));
  }

  // ── Init / Bootstrap ───────────────────────────────────────────
  parts.push([
    ``,
    `  // ── BOOTSTRAP ─────────────────────────────────────────────────────────────`,
    `  // Handle only actions marketplace.js does NOT cover.`,
    `  // install / uninstall / open are handled by marketplace.js _msgHandler`,
    `  // to avoid double-firing when the marketplace iframe is open.`,
    `  window.addEventListener('message', function (e) {`,
    `    if (!e.data || e.data.type !== 'etb_plugin_action') return;`,
    `    var action = e.data.action;`,
    `    if (action === 'github_add') {`,
    `      ETB.marketplace.close(); ETB.githubAdd.open();`,
    `    } else if (action === 'github_add_url') {`,
    `      ETB.marketplace.close(); ETB.githubAdd.open(e.data.url || '');`,
    `    } else if (action === 'hf_add') {`,
    `      ETB.marketplace.close(); ETB.hfAdd.open();`,
    `    } else if (action === 'hf_add_url') {`,
    `      ETB.marketplace.close(); ETB.hfAdd.open(e.data.url || '');`,
    `    }`,
    `  });`,
    ``,
    `  // Mount toolbar when DOM is ready`,
    `  function _mount() {`,
    `    // Remove legacy toolbar if present`,
    `    ['#_eFtb', '#ext-toolbar', '#_etbsw', '#_etbpop'].forEach(function (sel) {`,
    `      var el = document.querySelector(sel);`,
    `      if (el && el.parentNode) el.parentNode.removeChild(el);`,
    `    });`,
    `    // Acquire API token from the live Extella session (in-memory only)`,
    `    ETB.auth.initFromSession();`,
    `    ETB.shell.init();`,
    `    ETB.tabs.init();`,
    `    // Best-effort: pull agent-installed plugins from the local file registry`,
    `    // (~/extella-plugins/_registry/*.json) via a device expert. Gated on a`,
    `    // valid session token so we never hit an empty-token 401 at boot (which`,
    `    // would pop the manual token modal). Offline falls back to the cache.`,
    `    try {`,
    `      ETB.auth.onToken(function () {`,
    `        // Pull the centrally-configured install agent (best-effort, KV mirror).`,
    `        ETB.api.syncInstallAgentFromKV();`,
    `        ETB.api.kvGet('_device_id')`,
    `          .then(function (r) {`,
    `            if (r && r.value) return r.value;`,
    `            try { return (window.extellaDesktop && typeof window.extellaDesktop.getDeviceID === 'function') ? window.extellaDesktop.getDeviceID() : null; }`,
    `            catch (e) { return null; }`,
    `          })`,
    `          .then(function (did) {`,
    `            if (!did) return;`,
    `            return ETB.registry.syncFromDevice(did).then(function (added) {`,
    `              if (added && added.length) ETB.tabs.refresh();`,
    `            });`,
    `          })`,
    `          .catch(function () {});`,
    `      });`,
    `    } catch (e) {}`,
    `  }`,
    ``,
    `  if (document.readyState === 'loading') {`,
    `    document.addEventListener('DOMContentLoaded', _mount);`,
    `  } else {`,
    `    _mount();`,
    `  }`,
    ``,
    `  // Expose ETB globally for debugging`,
    `  window.ETB = ETB;`,
    ``
  ].join('\n'));

  // ── IIFE end ───────────────────────────────────────────────────
  parts.push(`})();\n`);

  return parts.join('');
}

// Indent every line of a string by `n` spaces
function indent(code, n) {
  const prefix = ' '.repeat(n);
  return code.split('\n').map(function (line) {
    return line.length ? prefix + line : line;
  }).join('\n');
}

// ── Step 3: Build plugins_manager.html ────────────────────────────────────
function buildMarketplace(plugins) {
  const template = readFile(path.join(PUBLIC, 'plugins_manager.html'));
  const _formHtml = buildForm(plugins);
  const _chatHtml = buildChat(plugins);
  const dataVar = `var BUILTIN_PLUGINS_DATA = ${JSON.stringify(plugins, null, 2)};`;
  // Function replacer required: string replacements treat `$'` / `$&` in plugin
  // expert code (regex patterns) as special patterns and corrupt the output.
  return template
    .replaceAll('__EXTELLA_LOGO_DATA__', getBrandLogoData())
    .replaceAll('__EXTELLA_DESKTOP_LOADER_DATA__', getDesktopLoaderData())
    .replace('/* __BUILTIN_PLUGINS_DATA__ */', function () { return dataVar; })
    .replace('/* __PLUGIN_FORM_HTML__ */', function () { return 'var _PLUGIN_FORM_HTML = ' + JSON.stringify(_formHtml).replace(/<\/script/gi, '<\\/script') + ';'; })
    .replace('/* __PLUGIN_CHAT_HTML__ */', function () { return 'var _PLUGIN_CHAT_HTML = ' + JSON.stringify(_chatHtml).replace(/<\/script/gi, '<\\/script') + ';'; });
}

// ── Step 4: Build plugin-chat.html (inject plugin data, same as marketplace) ──
function buildChat(plugins) {
  const template = readFile(path.join(PUBLIC, 'plugin-chat.html'));
  const dataVar = `var BUILTIN_PLUGINS_DATA = ${JSON.stringify(plugins, null, 2)};`;
  return template
    .replaceAll('__EXTELLA_LOGO_DATA__', getBrandLogoData())
    .replace('/* __BUILTIN_PLUGINS_DATA__ */', function () { return dataVar; });
}

// ── Step 4b: Build plugin-form.html (inject plugin data) ──────────────────
function buildForm(plugins) {
  const template = readFile(path.join(PUBLIC, 'plugin-form.html'));
  const dataVar = `var BUILTIN_PLUGINS_DATA = ${JSON.stringify(plugins, null, 2)};`;
  return template
    .replaceAll('__EXTELLA_LOGO_DATA__', getBrandLogoData())
    .replace('/* __BUILTIN_PLUGINS_DATA__ */', function () { return dataVar; });
}

function getBrandLogoData() {
  return fs.existsSync(BRAND_LOGO)
    ? 'data:image/png;base64,' + fs.readFileSync(BRAND_LOGO).toString('base64')
    : '';
}

function getDesktopLoaderData() {
  return fs.existsSync(DESKTOP_LOADER)
    ? 'data:video/webm;base64,' + fs.readFileSync(DESKTOP_LOADER).toString('base64')
    : '';
}

// ── Step 5: Build the embedded Library SPA ─────────────────────────────────
// Reads the Library module's single-file Vite build (../modules/library/dist/
// index.html) and splices a synchronous shim into <head> that lifts credentials
// from the URL hash into window.__MB_* BEFORE the React bundle boots — so the
// SPA's first API request already carries the token (no race with React Query).
//
// IMPORTANT: the SPA routes with createHashRouter, so it reads location.hash as
// the route. The shim therefore STRIPS the credential hash right after reading
// it (history.replaceState) so the router boots on a clean hash (→ /rules)
// instead of choking on `#token=…` and rendering a blank screen.
//
// Returns '' (with a warning) when the build hasn't been produced yet; the
// Library tab then no-ops instead of breaking the toolbar build.
const LIBRARY_DIST = path.join(ROOT, '..', 'modules', 'library', 'dist', 'index.html');

function buildLibrary() {
  if (!fs.existsSync(LIBRARY_DIST)) {
    console.warn(`  ⚠ Library build not found at ${path.relative(ROOT, LIBRARY_DIST)} ` +
      `— run \`npm run build -w @extella/library\` first. Library tab will be empty.`);
    return '';
  }
  const html = readFile(LIBRARY_DIST);
  const shim = [
    '<script>(function(){try{',
    'var h=new URLSearchParams((location.hash||"").replace(/^#/,""));',
    'if(h.get("token"))window.__MB_TOKEN__=h.get("token");',
    'if(h.get("base"))window.__MB_BASE_URL__=h.get("base");',
    'if(h.get("profile"))window.__MB_PROFILE_ID__=h.get("profile");',
    'if(h.get("agent"))window.__MB_AGENT_ID__=h.get("agent");',
    'if(h.get("theme"))window.__MB_THEME__=h.get("theme");',
    // Strip credentials from the hash so HashRouter boots on a clean route.
    // href.split("#") is robust for blob: URLs (unlike location.pathname).
    'history.replaceState(null,"",location.href.split("#")[0]);',
    '}catch(e){}})();</script>'
  ].join('');
  if (html.indexOf('<head>') !== -1) {
    return html.replace('<head>', '<head>' + shim);
  }
  // No literal <head> — prepend; still runs before the body module script.
  console.warn('  ⚠ Library build has no <head> tag — prepending credential shim.');
  return shim + html;
}

// ── Main build ─────────────────────────────────────────────────────────────
function build() {
  console.log('\n🔧 Extella Toolbar — Building...\n');

  const plugins = loadPlugins();

  console.log('\n📦 Writing output files:');
  writeFile(path.join(OUT, 'toolbar.js'), buildToolbar(plugins));
  writeFile(path.join(OUT, 'plugins_manager.html'), buildMarketplace(plugins));
  writeFile(path.join(OUT, 'plugin-chat.html'), buildChat(plugins));
  writeFile(path.join(OUT, 'plugin-form.html'), buildForm(plugins));

  writeFile(path.join(ROOT, 'dist_plugins_manager.html'), buildMarketplace(plugins));

  // Страж синтаксиса: одна битая запятая в инлайн-скрипте = белый экран витрины
  // у всех пользователей. Компилируем каждый <script> собранных страниц —
  // ошибка валит сборку с точной строкой, а не молча уезжает в прод.
  const vm = require('vm');
  ['plugins_manager.html', 'plugin-chat.html', 'plugin-form.html'].forEach(function (f) {
    const html = fs.readFileSync(path.join(OUT, f), 'utf8');
    (html.match(/<script>[\s\S]*?<\/script>/g) || []).forEach(function (block, i) {
      const code = block.slice('<script>'.length, -'</script>'.length);
      try { new vm.Script(code, { filename: f + '#script' + i }); }
      catch (e) { throw new Error('инлайн-скрипт сломан: ' + f + ' → ' + e.message); }
    });
  });
  console.log('  ✓ Инлайн-скрипты страниц проверены (vm.Script)');

  // Страж канона имён: слова, которые уже переименовывали, не должны
  // возвращаться в видимые тексты — мержи старых веток их воскрешают
  // (случалось: «Визард» и «Сервисы» вернулись со слиянием ws-ui).
  // Комментарии кода из проверки исключены. Список расширять по мере решений:
  // «Фабрика»/«ассистент»/«бот» пока не включены — есть легитимные употребления.
  const CANON_BANNED = [/Визард/, /Строител/, /крут[ия]тся/];
  ['plugins_manager.html', 'plugin-chat.html', 'plugin-form.html'].forEach(function (f) {
    const raw = fs.readFileSync(path.join(OUT, f), 'utf8');
    const scrubbed = raw.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/[^\n]*/g, '$1');
    CANON_BANNED.forEach(function (rx) {
      const m = scrubbed.match(rx);
      if (m) {
        const idx = scrubbed.indexOf(m[0]);
        const ctx = scrubbed.slice(Math.max(0, idx - 60), idx + 60).replace(/\s+/g, ' ');
        throw new Error('канон имён нарушен: «' + m[0] + '» в ' + f + ' → …' + ctx + '…');
      }
    });
  });
  console.log('  ✓ Канон имён соблюдён (Визард/Строитель/«крутятся» не встречаются)');

  console.log('\n✅ Build complete!');

  // When invoked by install.sh (which runs this build, then deploys), skip the
  // deploy hints — the installer prints its own next steps, and pointing the
  // user back at the installer they're already inside would be circular.
  if (process.env.ETB_FROM_INSTALLER) return;

  console.log('\nDeploy — run ./install.sh from the repo root to build + deploy in one step,');
  console.log('or copy toolbar.js manually (plugin UIs are embedded — no ~/.extella/plugins):');
  console.log('  cp "' + path.join(OUT, 'toolbar.js') + '" \\');
  console.log('     ~/Library/Application\\ Support/extella-desktop/toolbar.js');
  console.log('  then Cmd+Q and reopen Extella Desktop.\n');
}

// ── Watch mode ─────────────────────────────────────────────────────────────
function watch() {
  build();
  const chokidar = (() => { try { return require('chokidar'); } catch(e) { return null; } })();
  if (!chokidar) {
    console.log('Install chokidar for watch mode: npm install chokidar');
    return;
  }
  const watcher = chokidar.watch([
    path.join(SRC, '**/*.js'),
    path.join(PLUGINS, '**/*.json'),
    path.join(PUBLIC, '**/*.html')
  ], { ignoreInitial: true });

  watcher.on('change', function (p) {
    console.log(`\n  Changed: ${path.relative(ROOT, p)}`);
    try { build(); } catch (e) { console.error('Build error:', e.message); }
  });
  console.log('Watching for changes... (Ctrl+C to stop)\n');
}

// ── CLI ────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
if (args.includes('--watch')) {
  watch();
} else {
  try {
    build();
  } catch (e) {
    console.error('\n❌ Build failed:', e.message);
    process.exit(1);
  }
}
